#!/usr/bin/python3
def print_matrix_integer(matrix=[[]]):
    for i in matrix:
        l = len(i) - 1
        for j in i:
            print("{:d}".format(j), end="")
            if l > 0:
                print("", end=" ")
                l-=1
        print()
